#!/usr/bin/env bash
# Generate the compose devnet definition (.devnet/docker/compose.yaml).
#
# Services are GENERATED and ENUMERATED, never `--scale`d: compose replicas
# share a service's volume, so scaled guardians would all be the same
# on-chain identity (same keyring, same encryption key), and two containers
# on one validator volume is a guaranteed double-sign
# (docs/planning/PENDING_CONTAINERISATION_PLAN.md §4).
#
# Env knobs (same defaults as the native devnet where one exists):
#   VALIDATOR_COUNT (default 1)   GUARDIAN_COUNT (default 24)
#   TIMEFLARE_BLOCK_TIME (6s)     CHAIN_ID (timeflare-test)
#   TIMEFLARE_DOCKER_PORT_OFFSET (0) — added to every published host port so
#                                      two compose devnets coexist
#   GUARDIAN_STAKE / GUARDIAN_FUNDING / GUARDIAN_AVAILABLE_UNTIL

set -euo pipefail

VALIDATOR_COUNT="${VALIDATOR_COUNT:-1}"
GUARDIAN_COUNT="${GUARDIAN_COUNT:-24}"
CHAIN_ID="${CHAIN_ID:-timeflare-test}"
BLOCK_TIME="${TIMEFLARE_BLOCK_TIME:-6s}"
PORT_OFFSET="${TIMEFLARE_DOCKER_PORT_OFFSET:-0}"
OUT="${1:?usage: $0 <output-compose-yaml>}"

GUARDIAN_STAKE="${GUARDIAN_STAKE:-50000000000uveil}"
GUARDIAN_FUNDING="${GUARDIAN_FUNDING:-55000000000uveil}"
# Protocol maximum (types.MaxAvailabilityWindow) — must match
# devnet/docker/init-guardians.sh, which consumes this via the container env.
GUARDIAN_AVAILABLE_UNTIL="${GUARDIAN_AVAILABLE_UNTIL:-5256000}"

mkdir -p "$(dirname "$OUT")"

port() { echo $(($1 + PORT_OFFSET)); }

{
cat <<EOF
# GENERATED by devnet/docker/generate-compose.sh — do not edit by hand.
# Regenerated on every 'make docker-up' from VALIDATOR_COUNT/GUARDIAN_COUNT.
name: timeflare

networks:
  timeflare:
    driver: bridge

volumes:
  # Authoritative genesis keyring — survives host-side wipes of .devnet/;
  # chain-init re-exports a host copy to ./home on every run
  chain-shared:
EOF
for ((i = 0; i < VALIDATOR_COUNT; i++)); do
    echo "  validator-$i-data:"
done
for g in $(seq 1 "$GUARDIAN_COUNT"); do
    printf "  guardian-%02d-data:\n" "$g"
done

cat <<EOF

services:
  chain-init:
    image: timeflare/tools:dev
    container_name: timeflare-chain-init
    entrypoint: ["bash", "/scripts/docker/init-chain.sh"]
    environment:
      CHAIN_ID: "$CHAIN_ID"
      VALIDATOR_COUNT: "$VALIDATOR_COUNT"
      TIMEFLARE_BLOCK_TIME: "$BLOCK_TIME"
    volumes:
      - ../../devnet:/scripts:ro
      - ./home:/shared
      - chain-shared:/chain-shared
EOF
for ((i = 0; i < VALIDATOR_COUNT; i++)); do
    echo "      - validator-$i-data:/data/validator-$i"
done
cat <<EOF
    networks: [timeflare]

EOF

for ((i = 0; i < VALIDATOR_COUNT; i++)); do
cat <<EOF
  validator-$i:
    image: timeflare/timeflared:dev
    container_name: timeflare-validator-$i
    command: ["start"]
    volumes:
      - validator-$i-data:/home/nonroot/.timeflare
    networks: [timeflare]
    depends_on:
      chain-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "timeflared", "status"]
      interval: 5s
      timeout: 4s
      retries: 12
      start_period: 15s
    restart: unless-stopped
    ports:
      - "$(port $((26657 + 10 * i))):26657"
EOF
    if [[ $i -eq 0 ]]; then
cat <<EOF
      - "$(port 9090):9090"
      - "$(port 1317):1317"
EOF
    fi
    echo ""
done

cat <<EOF
  guardian-init:
    image: timeflare/tools:dev
    container_name: timeflare-guardian-init
    entrypoint: ["bash", "/scripts/docker/init-guardians.sh"]
    environment:
      CHAIN_ID: "$CHAIN_ID"
      GUARDIAN_COUNT: "$GUARDIAN_COUNT"
      RPC_ENDPOINT: "http://validator-0:26657"
      GRPC_ENDPOINT: "validator-0:9090"
      GUARDIAN_STAKE: "$GUARDIAN_STAKE"
      GUARDIAN_FUNDING: "$GUARDIAN_FUNDING"
      GUARDIAN_AVAILABLE_UNTIL: "$GUARDIAN_AVAILABLE_UNTIL"
    volumes:
      - ../../devnet:/scripts:ro
      - ./home:/shared
EOF
for g in $(seq 1 "$GUARDIAN_COUNT"); do
    printf "      - guardian-%02d-data:/homes/guardian-%02d/.timeflare/guardian\n" "$g" "$g"
done
cat <<EOF
    networks: [timeflare]
    depends_on:
      validator-0:
        condition: service_healthy

EOF

for g in $(seq 1 "$GUARDIAN_COUNT"); do
    name=$(printf "guardian-%02d" "$g")
cat <<EOF
  $name:
    image: timeflare/guardiand:dev
    container_name: timeflare-$name
    command: ["start"]
    environment:
      # config.yaml on the volume carries the generated identity; these
      # re-point the init-container-absolute paths at this container's mount
      # (precedence env > file)
      GUARDIAN_KEYRING_DIR: /home/nonroot/.timeflare/guardian/keyring
      GUARDIAN_KEYRING_PASSPHRASE: /home/nonroot/.timeflare/guardian/keyring_passphrase
      GUARDIAN_ENCRYPTION_PRIVATE_KEY_PATH: /home/nonroot/.timeflare/guardian/private_key
    volumes:
      - $name-data:/home/nonroot/.timeflare/guardian
    networks: [timeflare]
    depends_on:
      guardian-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "guardiand", "health", "--timeout", "3"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 20s
    restart: unless-stopped

EOF
done
} > "$OUT"

echo "generated $OUT ($VALIDATOR_COUNT validator(s), $GUARDIAN_COUNT guardians, port offset $PORT_OFFSET)"
