// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: timeflare/secrets/v1/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// StoredShare is a genesis entry for one guardian's encrypted share record.
type StoredShare struct {
	SecretId        string          `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	GuardianAddress string          `protobuf:"bytes,2,opt,name=guardian_address,json=guardianAddress,proto3" json:"guardian_address,omitempty"`
	Data            SecretShareData `protobuf:"bytes,3,opt,name=data,proto3" json:"data"`
}

func (m *StoredShare) Reset()         { *m = StoredShare{} }
func (m *StoredShare) String() string { return proto.CompactTextString(m) }
func (*StoredShare) ProtoMessage()    {}
func (*StoredShare) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a0de34f6aedf70, []int{0}
}
func (m *StoredShare) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredShare) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredShare.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredShare) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredShare.Merge(m, src)
}
func (m *StoredShare) XXX_Size() int {
	return m.Size()
}
func (m *StoredShare) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredShare.DiscardUnknown(m)
}

var xxx_messageInfo_StoredShare proto.InternalMessageInfo

func (m *StoredShare) GetSecretId() string {
	if m != nil {
		return m.SecretId
	}
	return ""
}

func (m *StoredShare) GetGuardianAddress() string {
	if m != nil {
		return m.GuardianAddress
	}
	return ""
}

func (m *StoredShare) GetData() SecretShareData {
	if m != nil {
		return m.Data
	}
	return SecretShareData{}
}

// StoredAssignment is a genesis entry for one guardian's assignment status record.
type StoredAssignment struct {
	SecretId        string           `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	GuardianAddress string           `protobuf:"bytes,2,opt,name=guardian_address,json=guardianAddress,proto3" json:"guardian_address,omitempty"`
	Record          AssignmentRecord `protobuf:"bytes,3,opt,name=record,proto3" json:"record"`
}

func (m *StoredAssignment) Reset()         { *m = StoredAssignment{} }
func (m *StoredAssignment) String() string { return proto.CompactTextString(m) }
func (*StoredAssignment) ProtoMessage()    {}
func (*StoredAssignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a0de34f6aedf70, []int{1}
}
func (m *StoredAssignment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredAssignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredAssignment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredAssignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredAssignment.Merge(m, src)
}
func (m *StoredAssignment) XXX_Size() int {
	return m.Size()
}
func (m *StoredAssignment) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredAssignment.DiscardUnknown(m)
}

var xxx_messageInfo_StoredAssignment proto.InternalMessageInfo

func (m *StoredAssignment) GetSecretId() string {
	if m != nil {
		return m.SecretId
	}
	return ""
}

func (m *StoredAssignment) GetGuardianAddress() string {
	if m != nil {
		return m.GuardianAddress
	}
	return ""
}

func (m *StoredAssignment) GetRecord() AssignmentRecord {
	if m != nil {
		return m.Record
	}
	return AssignmentRecord{}
}

// StoredReveal is a genesis entry for one revealed share (the guardian
// address is carried inside the RevealedShare).
type StoredReveal struct {
	SecretId string        `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Reveal   RevealedShare `protobuf:"bytes,2,opt,name=reveal,proto3" json:"reveal"`
}

func (m *StoredReveal) Reset()         { *m = StoredReveal{} }
func (m *StoredReveal) String() string { return proto.CompactTextString(m) }
func (*StoredReveal) ProtoMessage()    {}
func (*StoredReveal) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a0de34f6aedf70, []int{2}
}
func (m *StoredReveal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredReveal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredReveal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredReveal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredReveal.Merge(m, src)
}
func (m *StoredReveal) XXX_Size() int {
	return m.Size()
}
func (m *StoredReveal) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredReveal.DiscardUnknown(m)
}

var xxx_messageInfo_StoredReveal proto.InternalMessageInfo

func (m *StoredReveal) GetSecretId() string {
	if m != nil {
		return m.SecretId
	}
	return ""
}

func (m *StoredReveal) GetReveal() RevealedShare {
	if m != nil {
		return m.Reveal
	}
	return RevealedShare{}
}

// EarlyRevealSlashEntry marks a guardian slashed for an early reveal on a
// secret — required at settlement to exclude the guardian from payouts, so it
// is genuine state, not derivable.
type EarlyRevealSlashEntry struct {
	SecretId        string `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	GuardianAddress string `protobuf:"bytes,2,opt,name=guardian_address,json=guardianAddress,proto3" json:"guardian_address,omitempty"`
}

func (m *EarlyRevealSlashEntry) Reset()         { *m = EarlyRevealSlashEntry{} }
func (m *EarlyRevealSlashEntry) String() string { return proto.CompactTextString(m) }
func (*EarlyRevealSlashEntry) ProtoMessage()    {}
func (*EarlyRevealSlashEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a0de34f6aedf70, []int{3}
}
func (m *EarlyRevealSlashEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EarlyRevealSlashEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EarlyRevealSlashEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EarlyRevealSlashEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EarlyRevealSlashEntry.Merge(m, src)
}
func (m *EarlyRevealSlashEntry) XXX_Size() int {
	return m.Size()
}
func (m *EarlyRevealSlashEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_EarlyRevealSlashEntry.DiscardUnknown(m)
}

var xxx_messageInfo_EarlyRevealSlashEntry proto.InternalMessageInfo

func (m *EarlyRevealSlashEntry) GetSecretId() string {
	if m != nil {
		return m.SecretId
	}
	return ""
}

func (m *EarlyRevealSlashEntry) GetGuardianAddress() string {
	if m != nil {
		return m.GuardianAddress
	}
	return ""
}

// StoredPayload is a genesis entry for one secret's payload ciphertext.
type StoredPayload struct {
	SecretId          string `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	PayloadCiphertext []byte `protobuf:"bytes,2,opt,name=payload_ciphertext,json=payloadCiphertext,proto3" json:"payload_ciphertext,omitempty"`
}

func (m *StoredPayload) Reset()         { *m = StoredPayload{} }
func (m *StoredPayload) String() string { return proto.CompactTextString(m) }
func (*StoredPayload) ProtoMessage()    {}
func (*StoredPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a0de34f6aedf70, []int{4}
}
func (m *StoredPayload) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredPayload.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredPayload.Merge(m, src)
}
func (m *StoredPayload) XXX_Size() int {
	return m.Size()
}
func (m *StoredPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredPayload.DiscardUnknown(m)
}

var xxx_messageInfo_StoredPayload proto.InternalMessageInfo

func (m *StoredPayload) GetSecretId() string {
	if m != nil {
		return m.SecretId
	}
	return ""
}

func (m *StoredPayload) GetPayloadCiphertext() []byte {
	if m != nil {
		return m.PayloadCiphertext
	}
	return nil
}

// GenesisState defines the secrets module's genesis state. The due-height
// queues and the creator index are derived state and are rebuilt on import.
type GenesisState struct {
	// secrets defines all the slim secret records stored at genesis.
	Secrets []*Secret `protobuf:"bytes,1,rep,name=secrets,proto3" json:"secrets,omitempty"`
	// guardians defines all the guardians registered at genesis.
	Guardians []*Guardian `protobuf:"bytes,2,rep,name=guardians,proto3" json:"guardians,omitempty"`
	// secret_shares defines the per-guardian encrypted share records.
	SecretShares []StoredShare `protobuf:"bytes,3,rep,name=secret_shares,json=secretShares,proto3" json:"secret_shares"`
	// secret_assignments defines the per-guardian assignment status records.
	SecretAssignments []StoredAssignment `protobuf:"bytes,4,rep,name=secret_assignments,json=secretAssignments,proto3" json:"secret_assignments"`
	// secret_reveals defines the revealed share records.
	SecretReveals []StoredReveal `protobuf:"bytes,5,rep,name=secret_reveals,json=secretReveals,proto3" json:"secret_reveals"`
	// early_reveal_slashes defines guardians slashed for early reveals on
	// still-live secrets.
	EarlyRevealSlashes []EarlyRevealSlashEntry `protobuf:"bytes,6,rep,name=early_reveal_slashes,json=earlyRevealSlashes,proto3" json:"early_reveal_slashes"`
	// secret_payloads defines the stored payload ciphertexts.
	SecretPayloads []StoredPayload `protobuf:"bytes,7,rep,name=secret_payloads,json=secretPayloads,proto3" json:"secret_payloads"`
	// secret_counter is the monotonic sequence that assigns secret IDs and
	// differentiates selection seeds. It is consensus state and must survive
	// export/import: it only ever climbs, and is deliberately independent of
	// the stored secrets (pruned secrets consumed counter values too — never
	// re-derive it from the secret set).
	SecretCounter uint64 `protobuf:"varint,8,opt,name=secret_counter,json=secretCounter,proto3" json:"secret_counter,omitempty"`
	// secret_tombstones defines the permanent tombstones of pruned secrets.
	// The prune queue is derived state: it is rebuilt on import from the
	// non-pruned terminal secrets' terminal_at + RetentionBlocks.
	SecretTombstones []StoredTombstone `protobuf:"bytes,9,rep,name=secret_tombstones,json=secretTombstones,proto3" json:"secret_tombstones"`
	// rebate_state is the recipient-rebate accrual state: the allowance
	// available to credit, the height it was last accrued to, and the total
	// credited but not yet collected. Consensus state that must survive
	// export/import — a lost allowance would re-accrue from zero, and a lost
	// reservation would let the pool promise funds twice.
	RebateState RebateState `protobuf:"bytes,11,opt,name=rebate_state,json=rebateState,proto3" json:"rebate_state"`
	// guardian_key_histories defines every guardian's append-only key-epoch
	// history. A guardian with no entries here gets epoch 0 synthesised from
	// its record on import (the pre-rotation migration path). The key
	// uniqueness index is derived state — rebuilt on import from the history.
	GuardianKeyHistories []StoredKeyHistoryEntry `protobuf:"bytes,10,rep,name=guardian_key_histories,json=guardianKeyHistories,proto3" json:"guardian_key_histories"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a0de34f6aedf70, []int{5}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetSecrets() []*Secret {
	if m != nil {
		return m.Secrets
	}
	return nil
}

func (m *GenesisState) GetGuardians() []*Guardian {
	if m != nil {
		return m.Guardians
	}
	return nil
}

func (m *GenesisState) GetSecretShares() []StoredShare {
	if m != nil {
		return m.SecretShares
	}
	return nil
}

func (m *GenesisState) GetSecretAssignments() []StoredAssignment {
	if m != nil {
		return m.SecretAssignments
	}
	return nil
}

func (m *GenesisState) GetSecretReveals() []StoredReveal {
	if m != nil {
		return m.SecretReveals
	}
	return nil
}

func (m *GenesisState) GetEarlyRevealSlashes() []EarlyRevealSlashEntry {
	if m != nil {
		return m.EarlyRevealSlashes
	}
	return nil
}

func (m *GenesisState) GetSecretPayloads() []StoredPayload {
	if m != nil {
		return m.SecretPayloads
	}
	return nil
}

func (m *GenesisState) GetSecretCounter() uint64 {
	if m != nil {
		return m.SecretCounter
	}
	return 0
}

func (m *GenesisState) GetSecretTombstones() []StoredTombstone {
	if m != nil {
		return m.SecretTombstones
	}
	return nil
}

func (m *GenesisState) GetRebateState() RebateState {
	if m != nil {
		return m.RebateState
	}
	return RebateState{}
}

func (m *GenesisState) GetGuardianKeyHistories() []StoredKeyHistoryEntry {
	if m != nil {
		return m.GuardianKeyHistories
	}
	return nil
}

// StoredKeyHistoryEntry is a genesis entry for one epoch of one guardian's
// key history.
type StoredKeyHistoryEntry struct {
	GuardianAddress string          `protobuf:"bytes,1,opt,name=guardian_address,json=guardianAddress,proto3" json:"guardian_address,omitempty"`
	Epoch           uint64          `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	Entry           KeyHistoryEntry `protobuf:"bytes,3,opt,name=entry,proto3" json:"entry"`
}

func (m *StoredKeyHistoryEntry) Reset()         { *m = StoredKeyHistoryEntry{} }
func (m *StoredKeyHistoryEntry) String() string { return proto.CompactTextString(m) }
func (*StoredKeyHistoryEntry) ProtoMessage()    {}
func (*StoredKeyHistoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a0de34f6aedf70, []int{6}
}
func (m *StoredKeyHistoryEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredKeyHistoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredKeyHistoryEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredKeyHistoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredKeyHistoryEntry.Merge(m, src)
}
func (m *StoredKeyHistoryEntry) XXX_Size() int {
	return m.Size()
}
func (m *StoredKeyHistoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredKeyHistoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_StoredKeyHistoryEntry proto.InternalMessageInfo

func (m *StoredKeyHistoryEntry) GetGuardianAddress() string {
	if m != nil {
		return m.GuardianAddress
	}
	return ""
}

func (m *StoredKeyHistoryEntry) GetEpoch() uint64 {
	if m != nil {
		return m.Epoch
	}
	return 0
}

func (m *StoredKeyHistoryEntry) GetEntry() KeyHistoryEntry {
	if m != nil {
		return m.Entry
	}
	return KeyHistoryEntry{}
}

// StoredTombstone pairs a pruned secret's id with its permanent tombstone
// for genesis export/import.
type StoredTombstone struct {
	SecretId  string          `protobuf:"bytes,1,opt,name=secret_id,json=secretId,proto3" json:"secret_id,omitempty"`
	Tombstone SecretTombstone `protobuf:"bytes,2,opt,name=tombstone,proto3" json:"tombstone"`
}

func (m *StoredTombstone) Reset()         { *m = StoredTombstone{} }
func (m *StoredTombstone) String() string { return proto.CompactTextString(m) }
func (*StoredTombstone) ProtoMessage()    {}
func (*StoredTombstone) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a0de34f6aedf70, []int{7}
}
func (m *StoredTombstone) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *StoredTombstone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_StoredTombstone.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *StoredTombstone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredTombstone.Merge(m, src)
}
func (m *StoredTombstone) XXX_Size() int {
	return m.Size()
}
func (m *StoredTombstone) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredTombstone.DiscardUnknown(m)
}

var xxx_messageInfo_StoredTombstone proto.InternalMessageInfo

func (m *StoredTombstone) GetSecretId() string {
	if m != nil {
		return m.SecretId
	}
	return ""
}

func (m *StoredTombstone) GetTombstone() SecretTombstone {
	if m != nil {
		return m.Tombstone
	}
	return SecretTombstone{}
}

// RebateState carries the recipient-rebate mechanism's accrual bookkeeping.
// See docs/spec.md "Recipient Rebate".
type RebateState struct {
	// Allowance available to credit, in uveil. Accrues from the rebate pool's
	// balance and is capped at RebateBurstBlocks of accrual.
	Allowance int64 `protobuf:"varint,1,opt,name=allowance,proto3" json:"allowance,omitempty"`
	// Height the allowance was last accrued to. Accrual is lazy: an idle block
	// does no work, and the gap is applied the next time a settlement consumes
	// the allowance.
	AccruedHeight int64 `protobuf:"varint,2,opt,name=accrued_height,json=accruedHeight,proto3" json:"accrued_height,omitempty"`
	// Total credited to secrets but not yet collected, in uveil. Reserved
	// against the pool balance so a credited rebate is always payable.
	Reserved int64 `protobuf:"varint,3,opt,name=reserved,proto3" json:"reserved,omitempty"`
}

func (m *RebateState) Reset()         { *m = RebateState{} }
func (m *RebateState) String() string { return proto.CompactTextString(m) }
func (*RebateState) ProtoMessage()    {}
func (*RebateState) Descriptor() ([]byte, []int) {
	return fileDescriptor_09a0de34f6aedf70, []int{8}
}
func (m *RebateState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RebateState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RebateState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RebateState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RebateState.Merge(m, src)
}
func (m *RebateState) XXX_Size() int {
	return m.Size()
}
func (m *RebateState) XXX_DiscardUnknown() {
	xxx_messageInfo_RebateState.DiscardUnknown(m)
}

var xxx_messageInfo_RebateState proto.InternalMessageInfo

func (m *RebateState) GetAllowance() int64 {
	if m != nil {
		return m.Allowance
	}
	return 0
}

func (m *RebateState) GetAccruedHeight() int64 {
	if m != nil {
		return m.AccruedHeight
	}
	return 0
}

func (m *RebateState) GetReserved() int64 {
	if m != nil {
		return m.Reserved
	}
	return 0
}

func init() {
	proto.RegisterType((*StoredShare)(nil), "timeflare.secrets.v1.StoredShare")
	proto.RegisterType((*StoredAssignment)(nil), "timeflare.secrets.v1.StoredAssignment")
	proto.RegisterType((*StoredReveal)(nil), "timeflare.secrets.v1.StoredReveal")
	proto.RegisterType((*EarlyRevealSlashEntry)(nil), "timeflare.secrets.v1.EarlyRevealSlashEntry")
	proto.RegisterType((*StoredPayload)(nil), "timeflare.secrets.v1.StoredPayload")
	proto.RegisterType((*GenesisState)(nil), "timeflare.secrets.v1.GenesisState")
	proto.RegisterType((*StoredKeyHistoryEntry)(nil), "timeflare.secrets.v1.StoredKeyHistoryEntry")
	proto.RegisterType((*StoredTombstone)(nil), "timeflare.secrets.v1.StoredTombstone")
	proto.RegisterType((*RebateState)(nil), "timeflare.secrets.v1.RebateState")
}

func init() {
	proto.RegisterFile("timeflare/secrets/v1/genesis.proto", fileDescriptor_09a0de34f6aedf70)
}

var fileDescriptor_09a0de34f6aedf70 = []byte{
	// 804 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x16, 0x2b, 0x59, 0xb6, 0x56, 0x72, 0x6d, 0x2f, 0xe4, 0x82, 0x70, 0x0d, 0x55, 0xa6, 0x61,
	0x43, 0x45, 0x5b, 0x09, 0x76, 0x81, 0x9e, 0x0a, 0x14, 0xf2, 0x4f, 0x6d, 0xb7, 0x01, 0x12, 0x50,
	0x39, 0x04, 0xf1, 0x81, 0x58, 0x91, 0x13, 0x91, 0x88, 0x44, 0x0a, 0x3b, 0x2b, 0xc5, 0x7c, 0x8b,
	0x9c, 0x72, 0xc9, 0x25, 0x8f, 0xe3, 0xa3, 0x8f, 0x39, 0x05, 0x81, 0xfd, 0x00, 0x79, 0x85, 0x80,
	0xbb, 0x2b, 0xd2, 0x30, 0x68, 0x9e, 0x7c, 0x23, 0x67, 0xbf, 0xf9, 0xe6, 0x9b, 0x9d, 0x6f, 0x77,
	0x89, 0x25, 0x82, 0x09, 0xbc, 0x19, 0x33, 0x0e, 0x3d, 0x04, 0x97, 0x83, 0xc0, 0xde, 0xfc, 0xa0,
	0x37, 0x82, 0x10, 0x30, 0xc0, 0xee, 0x94, 0x47, 0x22, 0xa2, 0xcd, 0x14, 0xd3, 0xd5, 0x98, 0xee,
	0xfc, 0x60, 0xab, 0x39, 0x8a, 0x46, 0x91, 0x04, 0xf4, 0x92, 0x2f, 0x85, 0xdd, 0xda, 0xc9, 0xe5,
	0x53, 0x9f, 0x1a, 0xb2, 0x9b, 0x5f, 0x72, 0xc6, 0xb8, 0x17, 0xb0, 0x50, 0x81, 0xac, 0x0f, 0x06,
	0xa9, 0x0f, 0x44, 0xc4, 0xc1, 0x1b, 0xf8, 0x8c, 0x03, 0xfd, 0x99, 0xd4, 0x14, 0xd8, 0x09, 0x3c,
	0xd3, 0x68, 0x1b, 0x9d, 0x9a, 0xbd, 0xa2, 0x02, 0x17, 0x1e, 0xfd, 0x95, 0xac, 0x2f, 0xd2, 0x1d,
	0xe6, 0x79, 0x1c, 0x10, 0xcd, 0x1f, 0x24, 0x66, 0x6d, 0x11, 0xef, 0xab, 0x30, 0xfd, 0x87, 0x54,
	0x3c, 0x26, 0x98, 0x59, 0x6e, 0x1b, 0x9d, 0xfa, 0xe1, 0x5e, 0x37, 0xaf, 0xb5, 0xee, 0x40, 0x7e,
	0xca, 0xc2, 0x27, 0x4c, 0xb0, 0xa3, 0xca, 0xf5, 0x97, 0x5f, 0x4a, 0xb6, 0x4c, 0xb4, 0x3e, 0x19,
	0x64, 0x5d, 0x09, 0xeb, 0x23, 0x06, 0xa3, 0x70, 0x02, 0xa1, 0x78, 0x32, 0x75, 0x27, 0xa4, 0xca,
	0xc1, 0x8d, 0xb8, 0xa7, 0xf5, 0xed, 0xe7, 0xeb, 0xcb, 0x2a, 0xdb, 0x12, 0xad, 0x05, 0xea, 0x5c,
	0x2b, 0x24, 0x0d, 0xa5, 0xd0, 0x86, 0x39, 0xb0, 0x71, 0xb1, 0xba, 0x7e, 0x52, 0x32, 0x81, 0x49,
	0x4d, 0xf5, 0xc3, 0xdd, 0xfc, 0x92, 0x8a, 0x4a, 0x4f, 0x23, 0xab, 0x97, 0x04, 0x2d, 0x87, 0x6c,
	0x9e, 0x32, 0x3e, 0x8e, 0x15, 0x66, 0x30, 0x66, 0xe8, 0x9f, 0x86, 0x82, 0xc7, 0x4f, 0xb5, 0x2d,
	0xd6, 0x25, 0x59, 0x55, 0x0d, 0xbd, 0x60, 0xf1, 0x38, 0x62, 0x5e, 0x31, 0xf1, 0x1f, 0x84, 0x4e,
	0x15, 0xce, 0x71, 0x83, 0xa9, 0x0f, 0x5c, 0xc0, 0x95, 0x90, 0xd4, 0x0d, 0x7b, 0x43, 0xaf, 0x1c,
	0xa7, 0x0b, 0xd6, 0xb7, 0x2a, 0x69, 0x9c, 0x29, 0xbf, 0x0f, 0x04, 0x13, 0x40, 0xff, 0x22, 0xcb,
	0xba, 0x71, 0xd3, 0x68, 0x97, 0x3b, 0xf5, 0xc3, 0xed, 0x22, 0x97, 0xd8, 0x0b, 0x30, 0xfd, 0x9b,
	0xd4, 0x16, 0xc2, 0x93, 0x4e, 0x92, 0xcc, 0x56, 0x7e, 0xe6, 0x99, 0x86, 0xd9, 0x59, 0x02, 0x7d,
	0x46, 0x56, 0x75, 0x4b, 0x98, 0x6c, 0x31, 0x9a, 0x65, 0xc9, 0xb0, 0xf3, 0x48, 0xed, 0xec, 0x68,
	0xe8, 0x61, 0x34, 0x30, 0x33, 0x2d, 0xd2, 0x4b, 0x42, 0x35, 0x1b, 0x4b, 0xbd, 0x82, 0x66, 0x45,
	0x52, 0xee, 0x17, 0x51, 0x66, 0xd6, 0xd2, 0xbc, 0x1b, 0x0a, 0x92, 0xc5, 0x91, 0x3e, 0x27, 0x3f,
	0x6a, 0x72, 0x65, 0x00, 0x34, 0x97, 0x24, 0xb1, 0x55, 0x44, 0xac, 0xcc, 0xa1, 0x49, 0x75, 0xab,
	0x2a, 0x86, 0xd4, 0x25, 0x4d, 0x48, 0x0c, 0xa4, 0xf9, 0x1c, 0x4c, 0x2c, 0x04, 0x68, 0x56, 0x25,
	0xed, 0x6f, 0xf9, 0xb4, 0xb9, 0x96, 0xd3, 0xfc, 0x14, 0x1e, 0x2c, 0x02, 0x52, 0x9b, 0xac, 0x69,
	0xd5, 0xda, 0x03, 0x68, 0x2e, 0x4b, 0xfe, 0xdd, 0x22, 0xd9, 0xda, 0x71, 0x9a, 0x57, 0xf7, 0xad,
	0x83, 0x48, 0xf7, 0xd2, 0x9d, 0x70, 0xa3, 0x59, 0x28, 0x80, 0x9b, 0x2b, 0x6d, 0xa3, 0x53, 0x59,
	0xf4, 0x77, 0xac, 0x82, 0xf4, 0x15, 0xd1, 0xbb, 0xe8, 0x88, 0x68, 0x32, 0x44, 0x11, 0x85, 0x80,
	0x66, 0x4d, 0x16, 0xdf, 0x2b, 0x2a, 0xfe, 0x72, 0x81, 0xd6, 0xe5, 0xd7, 0x15, 0x22, 0x0d, 0x23,
	0xfd, 0x8f, 0x34, 0x38, 0x0c, 0x99, 0x00, 0x07, 0x13, 0xef, 0x9a, 0x75, 0x79, 0x86, 0x77, 0x1e,
	0x3b, 0xc3, 0x09, 0x52, 0x9a, 0x5c, 0x13, 0xd6, 0x79, 0x16, 0xa2, 0x23, 0xf2, 0x53, 0x7a, 0x20,
	0xdf, 0x42, 0xec, 0xf8, 0x01, 0x8a, 0x88, 0x07, 0x80, 0x26, 0x29, 0x9a, 0x83, 0x92, 0xfa, 0x3f,
	0xc4, 0xe7, 0x12, 0x1f, 0xdf, 0x9f, 0x43, 0x73, 0x41, 0x98, 0x2e, 0x07, 0x80, 0xd6, 0x47, 0x83,
	0x6c, 0xe6, 0x66, 0xe5, 0xde, 0x09, 0x46, 0xfe, 0x55, 0xd9, 0x24, 0x4b, 0x30, 0x8d, 0x5c, 0x5f,
	0x1e, 0xec, 0x8a, 0xad, 0x7e, 0x68, 0x9f, 0x2c, 0x41, 0xc2, 0x54, 0x7c, 0xbf, 0xe7, 0x8b, 0x55,
	0x99, 0x56, 0x4c, 0xd6, 0x1e, 0xec, 0x7e, 0xf1, 0x75, 0x73, 0x41, 0x6a, 0xe9, 0x54, 0xf5, 0x1d,
	0x5a, 0xf8, 0xac, 0x3c, 0x1c, 0x6a, 0x96, 0x6d, 0x85, 0xa4, 0x7e, 0x6f, 0x46, 0x74, 0x9b, 0xd4,
	0xd8, 0x78, 0x1c, 0xbd, 0x63, 0xa1, 0x0b, 0xb2, 0x6c, 0xd9, 0xce, 0x02, 0x89, 0xf7, 0x98, 0xeb,
	0xf2, 0x19, 0x78, 0x8e, 0x0f, 0xc1, 0xc8, 0x57, 0x57, 0x5c, 0xd9, 0x5e, 0xd5, 0xd1, 0x73, 0x19,
	0xa4, 0x5b, 0x64, 0x85, 0x03, 0x02, 0x9f, 0x83, 0x7a, 0x54, 0xca, 0x76, 0xfa, 0x7f, 0xf4, 0xef,
	0xf5, 0x6d, 0xcb, 0xb8, 0xb9, 0x6d, 0x19, 0x5f, 0x6f, 0x5b, 0xc6, 0xfb, 0xbb, 0x56, 0xe9, 0xe6,
	0xae, 0x55, 0xfa, 0x7c, 0xd7, 0x2a, 0xbd, 0xfe, 0x7d, 0x14, 0x08, 0x7f, 0x36, 0xec, 0xba, 0xd1,
	0xa4, 0x97, 0xf6, 0x12, 0x44, 0x3d, 0xd7, 0x67, 0x41, 0xd8, 0xbb, 0x4a, 0x1f, 0x6e, 0x11, 0x4f,
	0x01, 0x87, 0x55, 0xf9, 0x66, 0xff, 0xf9, 0x3d, 0x00, 0x00, 0xff, 0xff, 0xde, 0x5a, 0x5b, 0xf1,
	0x4d, 0x08, 0x00, 0x00,
}

func (m *StoredShare) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredShare) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredShare) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Data.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.GuardianAddress) > 0 {
		i -= len(m.GuardianAddress)
		copy(dAtA[i:], m.GuardianAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.GuardianAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SecretId) > 0 {
		i -= len(m.SecretId)
		copy(dAtA[i:], m.SecretId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.SecretId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredAssignment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredAssignment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredAssignment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Record.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.GuardianAddress) > 0 {
		i -= len(m.GuardianAddress)
		copy(dAtA[i:], m.GuardianAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.GuardianAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SecretId) > 0 {
		i -= len(m.SecretId)
		copy(dAtA[i:], m.SecretId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.SecretId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredReveal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredReveal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredReveal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Reveal.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.SecretId) > 0 {
		i -= len(m.SecretId)
		copy(dAtA[i:], m.SecretId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.SecretId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EarlyRevealSlashEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EarlyRevealSlashEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EarlyRevealSlashEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.GuardianAddress) > 0 {
		i -= len(m.GuardianAddress)
		copy(dAtA[i:], m.GuardianAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.GuardianAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SecretId) > 0 {
		i -= len(m.SecretId)
		copy(dAtA[i:], m.SecretId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.SecretId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredPayload) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredPayload) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredPayload) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PayloadCiphertext) > 0 {
		i -= len(m.PayloadCiphertext)
		copy(dAtA[i:], m.PayloadCiphertext)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.PayloadCiphertext)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.SecretId) > 0 {
		i -= len(m.SecretId)
		copy(dAtA[i:], m.SecretId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.SecretId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.RebateState.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x5a
	if len(m.GuardianKeyHistories) > 0 {
		for iNdEx := len(m.GuardianKeyHistories) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.GuardianKeyHistories[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.SecretTombstones) > 0 {
		for iNdEx := len(m.SecretTombstones) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SecretTombstones[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if m.SecretCounter != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.SecretCounter))
		i--
		dAtA[i] = 0x40
	}
	if len(m.SecretPayloads) > 0 {
		for iNdEx := len(m.SecretPayloads) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SecretPayloads[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.EarlyRevealSlashes) > 0 {
		for iNdEx := len(m.EarlyRevealSlashes) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.EarlyRevealSlashes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.SecretReveals) > 0 {
		for iNdEx := len(m.SecretReveals) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SecretReveals[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.SecretAssignments) > 0 {
		for iNdEx := len(m.SecretAssignments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SecretAssignments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.SecretShares) > 0 {
		for iNdEx := len(m.SecretShares) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.SecretShares[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.Guardians) > 0 {
		for iNdEx := len(m.Guardians) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Guardians[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Secrets) > 0 {
		for iNdEx := len(m.Secrets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Secrets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *StoredKeyHistoryEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredKeyHistoryEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredKeyHistoryEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Entry.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.Epoch != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Epoch))
		i--
		dAtA[i] = 0x10
	}
	if len(m.GuardianAddress) > 0 {
		i -= len(m.GuardianAddress)
		copy(dAtA[i:], m.GuardianAddress)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.GuardianAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *StoredTombstone) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *StoredTombstone) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *StoredTombstone) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Tombstone.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.SecretId) > 0 {
		i -= len(m.SecretId)
		copy(dAtA[i:], m.SecretId)
		i = encodeVarintGenesis(dAtA, i, uint64(len(m.SecretId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RebateState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RebateState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RebateState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Reserved != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Reserved))
		i--
		dAtA[i] = 0x18
	}
	if m.AccruedHeight != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.AccruedHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.Allowance != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.Allowance))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *StoredShare) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SecretId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.GuardianAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Data.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *StoredAssignment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SecretId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.GuardianAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Record.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *StoredReveal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SecretId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Reveal.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *EarlyRevealSlashEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SecretId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.GuardianAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *StoredPayload) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SecretId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = len(m.PayloadCiphertext)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Secrets) > 0 {
		for _, e := range m.Secrets {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Guardians) > 0 {
		for _, e := range m.Guardians {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SecretShares) > 0 {
		for _, e := range m.SecretShares {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SecretAssignments) > 0 {
		for _, e := range m.SecretAssignments {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SecretReveals) > 0 {
		for _, e := range m.SecretReveals {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.EarlyRevealSlashes) > 0 {
		for _, e := range m.EarlyRevealSlashes {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.SecretPayloads) > 0 {
		for _, e := range m.SecretPayloads {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.SecretCounter != 0 {
		n += 1 + sovGenesis(uint64(m.SecretCounter))
	}
	if len(m.SecretTombstones) > 0 {
		for _, e := range m.SecretTombstones {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.GuardianKeyHistories) > 0 {
		for _, e := range m.GuardianKeyHistories {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	l = m.RebateState.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *StoredKeyHistoryEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.GuardianAddress)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	if m.Epoch != 0 {
		n += 1 + sovGenesis(uint64(m.Epoch))
	}
	l = m.Entry.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *StoredTombstone) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.SecretId)
	if l > 0 {
		n += 1 + l + sovGenesis(uint64(l))
	}
	l = m.Tombstone.Size()
	n += 1 + l + sovGenesis(uint64(l))
	return n
}

func (m *RebateState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Allowance != 0 {
		n += 1 + sovGenesis(uint64(m.Allowance))
	}
	if m.AccruedHeight != 0 {
		n += 1 + sovGenesis(uint64(m.AccruedHeight))
	}
	if m.Reserved != 0 {
		n += 1 + sovGenesis(uint64(m.Reserved))
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *StoredShare) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredShare: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredShare: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardianAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuardianAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Data.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredAssignment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredAssignment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredAssignment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardianAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuardianAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Record", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Record.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredReveal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredReveal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredReveal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reveal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Reveal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EarlyRevealSlashEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EarlyRevealSlashEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EarlyRevealSlashEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardianAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuardianAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredPayload) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredPayload: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredPayload: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PayloadCiphertext", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PayloadCiphertext = append(m.PayloadCiphertext[:0], dAtA[iNdEx:postIndex]...)
			if m.PayloadCiphertext == nil {
				m.PayloadCiphertext = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Secrets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Secrets = append(m.Secrets, &Secret{})
			if err := m.Secrets[len(m.Secrets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Guardians", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Guardians = append(m.Guardians, &Guardian{})
			if err := m.Guardians[len(m.Guardians)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretShares", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretShares = append(m.SecretShares, StoredShare{})
			if err := m.SecretShares[len(m.SecretShares)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretAssignments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretAssignments = append(m.SecretAssignments, StoredAssignment{})
			if err := m.SecretAssignments[len(m.SecretAssignments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretReveals", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretReveals = append(m.SecretReveals, StoredReveal{})
			if err := m.SecretReveals[len(m.SecretReveals)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarlyRevealSlashes", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EarlyRevealSlashes = append(m.EarlyRevealSlashes, EarlyRevealSlashEntry{})
			if err := m.EarlyRevealSlashes[len(m.EarlyRevealSlashes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretPayloads", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretPayloads = append(m.SecretPayloads, StoredPayload{})
			if err := m.SecretPayloads[len(m.SecretPayloads)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretCounter", wireType)
			}
			m.SecretCounter = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SecretCounter |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretTombstones", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretTombstones = append(m.SecretTombstones, StoredTombstone{})
			if err := m.SecretTombstones[len(m.SecretTombstones)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardianKeyHistories", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuardianKeyHistories = append(m.GuardianKeyHistories, StoredKeyHistoryEntry{})
			if err := m.GuardianKeyHistories[len(m.GuardianKeyHistories)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RebateState", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RebateState.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredKeyHistoryEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredKeyHistoryEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredKeyHistoryEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field GuardianAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.GuardianAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Epoch", wireType)
			}
			m.Epoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Epoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Entry", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Entry.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *StoredTombstone) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: StoredTombstone: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: StoredTombstone: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SecretId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SecretId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tombstone", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Tombstone.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RebateState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RebateState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RebateState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Allowance", wireType)
			}
			m.Allowance = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Allowance |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccruedHeight", wireType)
			}
			m.AccruedHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AccruedHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserved", wireType)
			}
			m.Reserved = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Reserved |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
