// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: timeflare/secrets/v1/guardian.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Guardian defines a registered guardian node.
//
// Economics: guardians maintain a deposited float of VEIL. `stake` is the float
// TOTAL held in module escrow; `locked_stake` is the portion currently locked as
// per-secret bonds. unlocked = stake - locked_stake; withdrawals are capped at
// unlocked. See docs/spec.md "Secret Economics & Slashing".
type Guardian struct {
	Address             string      `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	EncryptionPublicKey []byte      `protobuf:"bytes,2,opt,name=encryption_public_key,json=encryptionPublicKey,proto3" json:"encryption_public_key,omitempty"`
	AvailableFrom       int64       `protobuf:"varint,3,opt,name=available_from,json=availableFrom,proto3" json:"available_from,omitempty"`
	AvailableUntil      int64       `protobuf:"varint,4,opt,name=available_until,json=availableUntil,proto3" json:"available_until,omitempty"`
	Stake               *types.Coin `protobuf:"bytes,5,opt,name=stake,proto3" json:"stake,omitempty"`
	AcceptingSecrets    bool        `protobuf:"varint,6,opt,name=accepting_secrets,json=acceptingSecrets,proto3" json:"accepting_secrets,omitempty"`
	LockedStake         *types.Coin `protobuf:"bytes,7,opt,name=locked_stake,json=lockedStake,proto3" json:"locked_stake,omitempty"`
	// Live bond multiplier k in hundredths (shares BumpScale): prices this
	// guardian's bonds, B = rate × distance × bump × k. Starts at the floor
	// (400 = 4.00); × 1.26 per slash, × 0.963 per correct reveal, truncating,
	// clamped to [400, 2400]. See docs/spec.md "The Per-Guardian Bond Multiplier k".
	BondK int64 `protobuf:"varint,8,opt,name=bond_k,json=bondK,proto3" json:"bond_k,omitempty"`
	// Denormalised count of currently locked per-secret bonds — the concurrency
	// cap gate (100): at the cap the guardian is not a selection candidate and
	// cannot lock further bonds. Asserted against the assignment store by the
	// invariant suite.
	ActiveBondCount int64 `protobuf:"varint,9,opt,name=active_bond_count,json=activeBondCount,proto3" json:"active_bond_count,omitempty"`
	// Current key epoch: 0 at registration, +1 per MsgGuardianRotateKey. The
	// encryption_public_key above is the current epoch's key (the O(1)
	// selection read); the full append-only history lives in the
	// GuardianKeyHistory store as (address, epoch) → KeyHistoryEntry.
	CurrentKeyEpoch uint64 `protobuf:"varint,10,opt,name=current_key_epoch,json=currentKeyEpoch,proto3" json:"current_key_epoch,omitempty"`
}

func (m *Guardian) Reset()         { *m = Guardian{} }
func (m *Guardian) String() string { return proto.CompactTextString(m) }
func (*Guardian) ProtoMessage()    {}
func (*Guardian) Descriptor() ([]byte, []int) {
	return fileDescriptor_a575a3da7bb23684, []int{0}
}
func (m *Guardian) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Guardian) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Guardian.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Guardian) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Guardian.Merge(m, src)
}
func (m *Guardian) XXX_Size() int {
	return m.Size()
}
func (m *Guardian) XXX_DiscardUnknown() {
	xxx_messageInfo_Guardian.DiscardUnknown(m)
}

var xxx_messageInfo_Guardian proto.InternalMessageInfo

func (m *Guardian) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Guardian) GetEncryptionPublicKey() []byte {
	if m != nil {
		return m.EncryptionPublicKey
	}
	return nil
}

func (m *Guardian) GetAvailableFrom() int64 {
	if m != nil {
		return m.AvailableFrom
	}
	return 0
}

func (m *Guardian) GetAvailableUntil() int64 {
	if m != nil {
		return m.AvailableUntil
	}
	return 0
}

func (m *Guardian) GetStake() *types.Coin {
	if m != nil {
		return m.Stake
	}
	return nil
}

func (m *Guardian) GetAcceptingSecrets() bool {
	if m != nil {
		return m.AcceptingSecrets
	}
	return false
}

func (m *Guardian) GetLockedStake() *types.Coin {
	if m != nil {
		return m.LockedStake
	}
	return nil
}

func (m *Guardian) GetBondK() int64 {
	if m != nil {
		return m.BondK
	}
	return 0
}

func (m *Guardian) GetActiveBondCount() int64 {
	if m != nil {
		return m.ActiveBondCount
	}
	return 0
}

func (m *Guardian) GetCurrentKeyEpoch() uint64 {
	if m != nil {
		return m.CurrentKeyEpoch
	}
	return 0
}

// KeyHistoryEntry is one epoch of a guardian's append-only key history.
// No entry is ever overwritten or deleted, and every key ever registered
// stays globally reserved forever — share material encrypted to it may
// still exist. See docs/spec.md "Guardian Key Rotation".
type KeyHistoryEntry struct {
	PublicKey []byte `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	// Height this epoch took effect: registration/rotation height + 1. The
	// epoch in force for a guardian at height h is the newest entry with
	// effective_from_height <= h — a pure function of the history, never
	// stored per-secret.
	EffectiveFromHeight int64 `protobuf:"varint,2,opt,name=effective_from_height,json=effectiveFromHeight,proto3" json:"effective_from_height,omitempty"`
}

func (m *KeyHistoryEntry) Reset()         { *m = KeyHistoryEntry{} }
func (m *KeyHistoryEntry) String() string { return proto.CompactTextString(m) }
func (*KeyHistoryEntry) ProtoMessage()    {}
func (*KeyHistoryEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_a575a3da7bb23684, []int{1}
}
func (m *KeyHistoryEntry) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *KeyHistoryEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_KeyHistoryEntry.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *KeyHistoryEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyHistoryEntry.Merge(m, src)
}
func (m *KeyHistoryEntry) XXX_Size() int {
	return m.Size()
}
func (m *KeyHistoryEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyHistoryEntry.DiscardUnknown(m)
}

var xxx_messageInfo_KeyHistoryEntry proto.InternalMessageInfo

func (m *KeyHistoryEntry) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *KeyHistoryEntry) GetEffectiveFromHeight() int64 {
	if m != nil {
		return m.EffectiveFromHeight
	}
	return 0
}

// GuardianEligibility is the selection filter's projection of a guardian,
// stored as the VALUE of the eligibility index (key: available_until, guardian
// address). It carries every field the per-secret filter needs so a candidate
// can be judged WITHOUT reading its full Guardian record.
//
// That is the whole point of the index. Reading the record per candidate would
// cost ~1,750 gas against ~336 for an index entry, and phase-1 candidate
// enumeration is metered inside the creator's transaction — an index that still
// read records would have to exclude ~68% of registrations merely to break even
// against walking the collection once.
//
// The denom is implied (DefaultDenom, as everywhere else in the module), so only
// the unlocked amount is stored. Every field is a projection of the record:
// GuardianEligibilityOf is the single place it is derived, SetGuardian the
// single place it is written.
type GuardianEligibility struct {
	// Absolute block height when the guardian starts accepting assignments. The
	// upper bound (available_until) is the index KEY, not a value field.
	AvailableFrom int64 `protobuf:"varint,1,opt,name=available_from,json=availableFrom,proto3" json:"available_from,omitempty"`
	// Concurrency-cap gate: at MaxActiveBondsPerGuardian the guardian is not a
	// candidate until an existing secret settles.
	ActiveBondCount int64 `protobuf:"varint,2,opt,name=active_bond_count,json=activeBondCount,proto3" json:"active_bond_count,omitempty"`
	// Live bond multiplier k in hundredths — prices THIS candidate's bond for the
	// secret being created, B = rate × distance × bump × k.
	BondK int64 `protobuf:"varint,3,opt,name=bond_k,json=bondK,proto3" json:"bond_k,omitempty"`
	// Float not currently locked as bonds (stake - locked_stake), the
	// affordability test's left-hand side. Derived, so it must be rewritten
	// whenever either component moves — which is why the index is maintained at
	// SetGuardian rather than at the call sites.
	Unlocked types.Coin `protobuf:"bytes,4,opt,name=unlocked,proto3" json:"unlocked"`
}

func (m *GuardianEligibility) Reset()         { *m = GuardianEligibility{} }
func (m *GuardianEligibility) String() string { return proto.CompactTextString(m) }
func (*GuardianEligibility) ProtoMessage()    {}
func (*GuardianEligibility) Descriptor() ([]byte, []int) {
	return fileDescriptor_a575a3da7bb23684, []int{2}
}
func (m *GuardianEligibility) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GuardianEligibility) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GuardianEligibility.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GuardianEligibility) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GuardianEligibility.Merge(m, src)
}
func (m *GuardianEligibility) XXX_Size() int {
	return m.Size()
}
func (m *GuardianEligibility) XXX_DiscardUnknown() {
	xxx_messageInfo_GuardianEligibility.DiscardUnknown(m)
}

var xxx_messageInfo_GuardianEligibility proto.InternalMessageInfo

func (m *GuardianEligibility) GetAvailableFrom() int64 {
	if m != nil {
		return m.AvailableFrom
	}
	return 0
}

func (m *GuardianEligibility) GetActiveBondCount() int64 {
	if m != nil {
		return m.ActiveBondCount
	}
	return 0
}

func (m *GuardianEligibility) GetBondK() int64 {
	if m != nil {
		return m.BondK
	}
	return 0
}

func (m *GuardianEligibility) GetUnlocked() types.Coin {
	if m != nil {
		return m.Unlocked
	}
	return types.Coin{}
}

func init() {
	proto.RegisterType((*Guardian)(nil), "timeflare.secrets.v1.Guardian")
	proto.RegisterType((*KeyHistoryEntry)(nil), "timeflare.secrets.v1.KeyHistoryEntry")
	proto.RegisterType((*GuardianEligibility)(nil), "timeflare.secrets.v1.GuardianEligibility")
}

func init() {
	proto.RegisterFile("timeflare/secrets/v1/guardian.proto", fileDescriptor_a575a3da7bb23684)
}

var fileDescriptor_a575a3da7bb23684 = []byte{
	// 541 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0xcf, 0x6b, 0xd4, 0x40,
	0x14, 0xde, 0xe9, 0xf6, 0xc7, 0x76, 0x5a, 0x5d, 0x4d, 0x5b, 0x88, 0x05, 0x63, 0xa8, 0x88, 0x41,
	0x21, 0x61, 0x2b, 0x82, 0xe0, 0x6d, 0x4b, 0xb5, 0xb2, 0x17, 0x49, 0xf1, 0xe2, 0x25, 0x4c, 0x26,
	0x6f, 0xb3, 0xc3, 0x66, 0x67, 0xc2, 0x64, 0x12, 0xcc, 0x7f, 0xe1, 0x1f, 0x24, 0x78, 0xed, 0xb1,
	0x47, 0x4f, 0x22, 0xbb, 0xff, 0x88, 0xcc, 0x24, 0xcd, 0xf6, 0xb0, 0xa0, 0xb7, 0xcc, 0xf7, 0x7d,
	0x2f, 0x6f, 0xbe, 0xf7, 0xcd, 0xc3, 0xcf, 0x15, 0x5b, 0xc0, 0x34, 0x23, 0x12, 0x82, 0x02, 0xa8,
	0x04, 0x55, 0x04, 0xd5, 0x28, 0x48, 0x4b, 0x22, 0x13, 0x46, 0xb8, 0x9f, 0x4b, 0xa1, 0x84, 0x75,
	0xdc, 0x89, 0xfc, 0x56, 0xe4, 0x57, 0xa3, 0x53, 0x87, 0x8a, 0x62, 0x21, 0x8a, 0x20, 0x26, 0x05,
	0x04, 0xd5, 0x28, 0x06, 0x45, 0x46, 0x01, 0x15, 0xac, 0xad, 0x3a, 0x3d, 0x4e, 0x45, 0x2a, 0xcc,
	0x67, 0xa0, 0xbf, 0x1a, 0xf4, 0xec, 0x67, 0x1f, 0x0f, 0x3e, 0xb6, 0xbf, 0xb7, 0x6c, 0xbc, 0x47,
	0x92, 0x44, 0x42, 0x51, 0xd8, 0xc8, 0x45, 0xde, 0x7e, 0x78, 0x77, 0xb4, 0xce, 0xf1, 0x09, 0x70,
	0x2a, 0xeb, 0x5c, 0x31, 0xc1, 0xa3, 0xbc, 0x8c, 0x33, 0x46, 0xa3, 0x39, 0xd4, 0xf6, 0x96, 0x8b,
	0xbc, 0xc3, 0xf0, 0x68, 0x4d, 0x7e, 0x36, 0xdc, 0x04, 0x6a, 0xeb, 0x05, 0x7e, 0x48, 0x2a, 0xc2,
	0x32, 0x12, 0x67, 0x10, 0x4d, 0xa5, 0x58, 0xd8, 0x7d, 0x17, 0x79, 0xfd, 0xf0, 0x41, 0x87, 0x7e,
	0x90, 0x62, 0x61, 0xbd, 0xc4, 0xc3, 0xb5, 0xac, 0xe4, 0x8a, 0x65, 0xf6, 0xb6, 0xd1, 0xad, 0xab,
	0xbf, 0x68, 0xd4, 0x7a, 0x8b, 0x77, 0x0a, 0x45, 0xe6, 0x60, 0xef, 0xb8, 0xc8, 0x3b, 0x38, 0x7f,
	0xe2, 0x37, 0x86, 0x7d, 0x6d, 0xd8, 0x6f, 0x0d, 0xfb, 0x17, 0x82, 0xf1, 0xf1, 0xf6, 0xcd, 0xef,
	0x67, 0x28, 0x6c, 0xd4, 0xd6, 0x6b, 0xfc, 0x98, 0x50, 0x0a, 0xb9, 0x62, 0x3c, 0x8d, 0xda, 0x79,
	0xd9, 0xbb, 0x2e, 0xf2, 0x06, 0xe1, 0xa3, 0x8e, 0xb8, 0x6e, 0x70, 0x6b, 0x8c, 0x0f, 0x33, 0x41,
	0xe7, 0x90, 0x44, 0x4d, 0xab, 0xbd, 0xff, 0x6b, 0x75, 0xd0, 0x14, 0x5d, 0x9b, 0x86, 0x27, 0x78,
	0x37, 0x16, 0x3c, 0x89, 0xe6, 0xf6, 0xc0, 0xf8, 0xd8, 0xd1, 0xa7, 0x89, 0xf5, 0x4a, 0xdf, 0x43,
	0xb1, 0x0a, 0x22, 0xc3, 0x52, 0x51, 0x72, 0x65, 0xef, 0x1b, 0xc5, 0xb0, 0x21, 0xc6, 0x82, 0x27,
	0x17, 0x1a, 0xd6, 0x5a, 0x5a, 0x4a, 0x09, 0x5c, 0xe9, 0x21, 0x47, 0x90, 0x0b, 0x3a, 0xb3, 0xb1,
	0x8b, 0xbc, 0xed, 0x70, 0xd8, 0x12, 0x13, 0xa8, 0x2f, 0x35, 0x7c, 0x96, 0xe0, 0xe1, 0x04, 0xea,
	0x2b, 0x56, 0x28, 0x21, 0xeb, 0x4b, 0xae, 0x64, 0x6d, 0x3d, 0xc5, 0xf8, 0x5e, 0x44, 0xc8, 0x44,
	0xb4, 0x9f, 0x77, 0xc1, 0xe8, 0x30, 0xa7, 0x53, 0x68, 0x2e, 0xa3, 0x83, 0x89, 0x66, 0xc0, 0xd2,
	0x99, 0x32, 0x61, 0xf6, 0xc3, 0xa3, 0x8e, 0xd4, 0xf9, 0x5c, 0x19, 0xea, 0xec, 0x07, 0xc2, 0x47,
	0x77, 0xef, 0xe4, 0x32, 0x63, 0x29, 0x8b, 0x59, 0xc6, 0xd4, 0xa6, 0x90, 0xd1, 0xa6, 0x90, 0x37,
	0x9a, 0xdf, 0xda, 0x6c, 0x7e, 0x3d, 0xbf, 0xfe, 0xfd, 0xf9, 0xbd, 0xc7, 0x83, 0x92, 0x37, 0x73,
	0x36, 0x0f, 0xe4, 0x9f, 0xb1, 0xf4, 0xc2, 0xae, 0x60, 0xfc, 0xe9, 0x66, 0xe9, 0xa0, 0xdb, 0xa5,
	0x83, 0xfe, 0x2c, 0x1d, 0xf4, 0x7d, 0xe5, 0xf4, 0x6e, 0x57, 0x4e, 0xef, 0xd7, 0xca, 0xe9, 0x7d,
	0x0d, 0x52, 0xa6, 0x66, 0x65, 0xec, 0x53, 0xb1, 0x08, 0x32, 0x80, 0x84, 0x54, 0xac, 0x78, 0x37,
	0x0a, 0xd6, 0x7b, 0xf8, 0xad, 0xdb, 0x44, 0x55, 0xe7, 0x50, 0xc4, 0xbb, 0x66, 0x71, 0xde, 0xfc,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x17, 0xc2, 0xd0, 0x3d, 0xab, 0x03, 0x00, 0x00,
}

func (m *Guardian) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Guardian) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Guardian) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CurrentKeyEpoch != 0 {
		i = encodeVarintGuardian(dAtA, i, uint64(m.CurrentKeyEpoch))
		i--
		dAtA[i] = 0x50
	}
	if m.ActiveBondCount != 0 {
		i = encodeVarintGuardian(dAtA, i, uint64(m.ActiveBondCount))
		i--
		dAtA[i] = 0x48
	}
	if m.BondK != 0 {
		i = encodeVarintGuardian(dAtA, i, uint64(m.BondK))
		i--
		dAtA[i] = 0x40
	}
	if m.LockedStake != nil {
		{
			size, err := m.LockedStake.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGuardian(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.AcceptingSecrets {
		i--
		if m.AcceptingSecrets {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	if m.Stake != nil {
		{
			size, err := m.Stake.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintGuardian(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if m.AvailableUntil != 0 {
		i = encodeVarintGuardian(dAtA, i, uint64(m.AvailableUntil))
		i--
		dAtA[i] = 0x20
	}
	if m.AvailableFrom != 0 {
		i = encodeVarintGuardian(dAtA, i, uint64(m.AvailableFrom))
		i--
		dAtA[i] = 0x18
	}
	if len(m.EncryptionPublicKey) > 0 {
		i -= len(m.EncryptionPublicKey)
		copy(dAtA[i:], m.EncryptionPublicKey)
		i = encodeVarintGuardian(dAtA, i, uint64(len(m.EncryptionPublicKey)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintGuardian(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *KeyHistoryEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *KeyHistoryEntry) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *KeyHistoryEntry) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EffectiveFromHeight != 0 {
		i = encodeVarintGuardian(dAtA, i, uint64(m.EffectiveFromHeight))
		i--
		dAtA[i] = 0x10
	}
	if len(m.PublicKey) > 0 {
		i -= len(m.PublicKey)
		copy(dAtA[i:], m.PublicKey)
		i = encodeVarintGuardian(dAtA, i, uint64(len(m.PublicKey)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *GuardianEligibility) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GuardianEligibility) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GuardianEligibility) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Unlocked.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGuardian(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.BondK != 0 {
		i = encodeVarintGuardian(dAtA, i, uint64(m.BondK))
		i--
		dAtA[i] = 0x18
	}
	if m.ActiveBondCount != 0 {
		i = encodeVarintGuardian(dAtA, i, uint64(m.ActiveBondCount))
		i--
		dAtA[i] = 0x10
	}
	if m.AvailableFrom != 0 {
		i = encodeVarintGuardian(dAtA, i, uint64(m.AvailableFrom))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintGuardian(dAtA []byte, offset int, v uint64) int {
	offset -= sovGuardian(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Guardian) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovGuardian(uint64(l))
	}
	l = len(m.EncryptionPublicKey)
	if l > 0 {
		n += 1 + l + sovGuardian(uint64(l))
	}
	if m.AvailableFrom != 0 {
		n += 1 + sovGuardian(uint64(m.AvailableFrom))
	}
	if m.AvailableUntil != 0 {
		n += 1 + sovGuardian(uint64(m.AvailableUntil))
	}
	if m.Stake != nil {
		l = m.Stake.Size()
		n += 1 + l + sovGuardian(uint64(l))
	}
	if m.AcceptingSecrets {
		n += 2
	}
	if m.LockedStake != nil {
		l = m.LockedStake.Size()
		n += 1 + l + sovGuardian(uint64(l))
	}
	if m.BondK != 0 {
		n += 1 + sovGuardian(uint64(m.BondK))
	}
	if m.ActiveBondCount != 0 {
		n += 1 + sovGuardian(uint64(m.ActiveBondCount))
	}
	if m.CurrentKeyEpoch != 0 {
		n += 1 + sovGuardian(uint64(m.CurrentKeyEpoch))
	}
	return n
}

func (m *KeyHistoryEntry) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PublicKey)
	if l > 0 {
		n += 1 + l + sovGuardian(uint64(l))
	}
	if m.EffectiveFromHeight != 0 {
		n += 1 + sovGuardian(uint64(m.EffectiveFromHeight))
	}
	return n
}

func (m *GuardianEligibility) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.AvailableFrom != 0 {
		n += 1 + sovGuardian(uint64(m.AvailableFrom))
	}
	if m.ActiveBondCount != 0 {
		n += 1 + sovGuardian(uint64(m.ActiveBondCount))
	}
	if m.BondK != 0 {
		n += 1 + sovGuardian(uint64(m.BondK))
	}
	l = m.Unlocked.Size()
	n += 1 + l + sovGuardian(uint64(l))
	return n
}

func sovGuardian(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGuardian(x uint64) (n int) {
	return sovGuardian(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Guardian) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGuardian
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Guardian: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Guardian: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGuardian
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGuardian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptionPublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGuardian
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGuardian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptionPublicKey = append(m.EncryptionPublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.EncryptionPublicKey == nil {
				m.EncryptionPublicKey = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableFrom", wireType)
			}
			m.AvailableFrom = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailableFrom |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableUntil", wireType)
			}
			m.AvailableUntil = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailableUntil |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stake", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGuardian
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGuardian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stake == nil {
				m.Stake = &types.Coin{}
			}
			if err := m.Stake.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AcceptingSecrets", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.AcceptingSecrets = bool(v != 0)
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LockedStake", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGuardian
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGuardian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LockedStake == nil {
				m.LockedStake = &types.Coin{}
			}
			if err := m.LockedStake.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondK", wireType)
			}
			m.BondK = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondK |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveBondCount", wireType)
			}
			m.ActiveBondCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveBondCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentKeyEpoch", wireType)
			}
			m.CurrentKeyEpoch = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentKeyEpoch |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGuardian(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGuardian
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *KeyHistoryEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGuardian
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: KeyHistoryEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: KeyHistoryEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicKey", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthGuardian
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthGuardian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PublicKey = append(m.PublicKey[:0], dAtA[iNdEx:postIndex]...)
			if m.PublicKey == nil {
				m.PublicKey = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EffectiveFromHeight", wireType)
			}
			m.EffectiveFromHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EffectiveFromHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipGuardian(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGuardian
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GuardianEligibility) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGuardian
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GuardianEligibility: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GuardianEligibility: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AvailableFrom", wireType)
			}
			m.AvailableFrom = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AvailableFrom |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ActiveBondCount", wireType)
			}
			m.ActiveBondCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ActiveBondCount |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BondK", wireType)
			}
			m.BondK = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BondK |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Unlocked", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGuardian
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGuardian
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Unlocked.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGuardian(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGuardian
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGuardian(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGuardian
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGuardian
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGuardian
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGuardian
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGuardian
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGuardian        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGuardian          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGuardian = fmt.Errorf("proto: unexpected end of group")
)
